//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhTHPT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DIEMSO
    {
        public string MAHOCSINH { get; set; }
        public string MAMONHOC { get; set; }
        public string MAHOCKY { get; set; }
        public string MALOP { get; set; }
        [Display(Name = "Điểm miệng")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Vui lòng nhập điểm miệng")]
        public Nullable<double> DIEMKTMIENG { get; set; }
        [Display(Name = "Điểm 15'")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Vui lòng nhập 15p'")]
        public Nullable<double> DIEMKT15PH { get; set; }
        [Display(Name = "Điểm 1 tiết")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Vui lòng nhập điểm 1 tiết")]
        public Nullable<double> DIEMKT45P { get; set; }
        [Display(Name = "Điểm cuối kỳ")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Vui lòng nhập điểm cuối kỳ")]
        public Nullable<double> DIEMTHICUOIKY { get; set; }
        [Display(Name = "Điểm TB")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Vui lòng nhập điểm Trung Bình")]
        public Nullable<double> DTB { get; set; }

        public virtual HOCSINH HOCSINH { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual HOCKY HOCKY { get; set; }
    }
}
