//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhTHPT.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GIAOVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GIAOVIEN()
        {
            this.LOPs = new HashSet<LOP>();
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
        [Display(Name = "Mã giáo viên")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Mã giáo viên không được để trống")]
        public string MAGIAOVIEN { get; set; }
        [Display(Name = "Họ tên")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Họ tên không được để trống")]
        public string TENGIAOVIEN { get; set; }
        public int MAGIOITINH { get; set; }
        [Display(Name = "Địa chỉ")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Địa chỉ không được để trống")]
        public string DIACHI { get; set; }
        [Display(Name = "Điện thoại")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Điện thoại không được để trống")]
        public string DIENTHOAI { get; set; }
        public string MAMONHOC { get; set; }

        public virtual GIOITINH GIOITINH { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOP> LOPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
