//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOCLUC
    {
        public string MAHOCLUC { get; set; }
        public string TENHOCLUC { get; set; }
        public double DIEMCANDUOI { get; set; }
        public double DIEMCANTREN { get; set; }
        public double DIEMKHONGCHE { get; set; }
    }
}
