//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KETQUAHOCKY
    {
        public string MAHOCSINH { get; set; }
        public string MAHOCKY { get; set; }
        public string MALOP { get; set; }
        public Nullable<double> DTB { get; set; }
    
        public virtual HOCSINH HOCSINH { get; set; }
        public virtual LOP LOP { get; set; }
    }
}
