//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyHocSinhTHPT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public int STT { get; set; }
        public string MANAMHOC { get; set; }
        public string MALOP { get; set; }
        public string MAMONHOC { get; set; }
        public string MAGIAOVIEN { get; set; }
    
        public virtual GIAOVIEN GIAOVIEN { get; set; }
        public virtual LOP LOP { get; set; }
        public virtual MONHOC MONHOC { get; set; }
        public virtual NAMHOC NAMHOC { get; set; }
    }
}
